import type { Profile } from './types';

export const emptyProfile: Profile = {
  basic_info: {
    first_name: '',
    last_name: '',
    email: '',
    phone: '',
    gender: '',
    github: '',
    linkedin: '',
    location: { city: '', country_code: '', max_distance_km: null },
    languages: [],
    experience_level: '',
    experience_since: '',
    job_search_status: '',
    soft_skills: [],
    cv_summary_bullets: [],
  },
  skills: {},
  work_experience: [],
  education: [],
  certifications: [],
  own_projects: [],
  red_flags: [
    { category: 'company_type', description: [] },
    { category: 'skills', description: [] },
    { category: 'other', description: [] },
  ],
  preferences: {
    salary: [],
    work_model: [],
    target_role: [],
    company_type: [],
    company_type_excluded: [],
    employment_type: [],
    industries: [],
    markets: [],
    learning_goals: [],
    max_office_days_per_week: null,
    office_location_cities: [],
  },
};
