export const API_BASE_URL =
  import.meta.env.VITE_API_BASE_URL ??
  'https://job-matcher-api-production.up.railway.app';
export const SHOW_TABS = false;

export const CONFIG = {
  auth: {
    google: true,
    facebook: false,
    microsoft: false,
    github: true,
  },
  use_template_cv: true,
  skills_suggestions: [
    'php',
    'jquery',
    'legacy',
    'cobol',
    'wordpress',
    '.net framework',
  ],
  currencies: [
    'USD',
    'PLN',
    'EUR',
    'GBP',
    'CHF',
    'NOK',
    'SEK',
    'DKK',
    'CAD',
    'AUD',
  ],
  industries: [
    'fintech',
    'saas',
    'developer_tools',
    'proptech',
    'e-commerce',
    'healthcare',
    'edtech',
    'gaming',
    'media',
    'travel',
    'logistics',
    'cybersecurity',
    'ai_ml',
    'blockchain',
    'martech',
  ],
  markets: [
    'Poland',
    'Europe',
    'USA',
    'UK',
    'Germany',
    'Netherlands',
    'Scandinavia',
    'remote_global',
  ],
  company_types: [
    'product',
    'startup',
    'outsourcing',
    'body_leasing',
    'agency',
    'consultancy',
    'corporation',
  ],
};
